{% set name = "opentelemetry-instrumentation-botocore" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_botocore-{{ version }}.tar.gz
  sha256: 5c4aafe58173041d4d9a07995bee1057c6763fef68552588b2a1f6913ba12870

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.43b0
    - opentelemetry-semantic-conventions ==0.43b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-propagator-aws-xray ==1.0.1
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore <1.31.81,~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-botocore
  summary: OpenTelemetry Botocore instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
