{% set name = "opentelemetry-instrumentation-botocore" %}
{% set version = "0.50b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_botocore-{{ version }}.tar.gz
  sha256: ffe856f24e1275cb9694bfdda49240d08a01f191b4725fdbd2b4622bea6aeed7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.50b0
    - opentelemetry-semantic-conventions ==0.50b0
    - opentelemetry-propagator-aws-xray ~=1.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - botocore ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-botocore
  summary: OpenTelemetry Botocore instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
