{% set name = "opentelemetry-instrumentation-botocore" %}
{% set version = "0.53b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_botocore-{{ version }}.tar.gz
  sha256: e0e323e39f3e0c9181a3ab258bcac4e4a28c6518e6ffdde57d533f98c7f65103

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.30
    - opentelemetry-instrumentation ==0.53b1
    - opentelemetry-semantic-conventions ==0.53b1
    - opentelemetry-propagator-aws-xray ~=1.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-botocore 
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - botocore ~=1.0
    # - botocore ~=1.0
    # - botocore ~=1.0
    # - botocore ~=1.0
    # - botocore ~=1.0
    # - botocore ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-botocore
  summary: OpenTelemetry Botocore instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
